
package wsproxy.proxy.onbase.com.bancodebogota.resources.classification.service;

import java.net.InetAddress;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.UnknownHostException;
import java.util.Collection;
import java.util.Hashtable;
import java.util.Iterator;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import admin.Contextos;
import baseDatos.ConsultaTablaEJB;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DocumentationItemManagementSvc", targetNamespace = "urn://bancodebogota.com/resources/classification/service/", wsdlLocation = "http://localhost/wsdl/DocumentationItemManagement.wsdl")
public class DocumentationItemManagementSvc
    extends Service
{

    private final static URL DOCUMENTATIONITEMMANAGEMENTSVC_WSDL_LOCATION;
    private final static WebServiceException DOCUMENTATIONITEMMANAGEMENTSVC_EXCEPTION;
    private final static QName DOCUMENTATIONITEMMANAGEMENTSVC_QNAME = new QName("urn://bancodebogota.com/resources/classification/service/", "DocumentationItemManagementSvc");

    static {
    	//jfore18
        URL url = null;
        WebServiceException e = null;
        String desarrollo = "AMBIENTE DESARROLLO";
        String pruebas = "AMBIENTE PRUEBAS";
        String produccion = "AMBIENTE PRODUCCION";
        String ambiente = null;
        try {
		    Contextos ctx = new Contextos();
			ConsultaTablaEJB consulta = (ConsultaTablaEJB)ctx.getContext("ConsultaTablaEJB");
			Collection c = consulta.consultarTabla(0,0,null, "SELECT NOMBRE_LARGO FROM LISTA_VALORES WHERE TIPO_DATO='28'");
			Iterator it = c.iterator();
			while ( it.hasNext() ){
			Hashtable h = (Hashtable)it.next();
			ambiente = (String) h.get("NOMBRE_LARGO");
			}
        }catch (Exception ex) {
            e = new WebServiceException(ex);
        }
        try {
        	System.out.println("Justificacion = "+ ambiente);
        	if (ambiente.equals(desarrollo)) {
            url = new URL("http://localhost/wsdl/DocumentationItemManagementDesarrollo.wsdl");
        	}
      
        	if(ambiente.equals(pruebas)){
        		url = new URL("http://localhost/wsdl/DocumentationItemManagementPruebas.wsdl");
        	}
        	if(ambiente.equals(produccion)){
            	url = new URL("http://localhost/wsdl/DocumentationItemManagementProduccion.wsdl");
        	}
            
        	
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        System.out.println("url"+url);
        DOCUMENTATIONITEMMANAGEMENTSVC_WSDL_LOCATION = url;
        DOCUMENTATIONITEMMANAGEMENTSVC_EXCEPTION = e;
    }

    public DocumentationItemManagementSvc() {
        super(__getWsdlLocation(), DOCUMENTATIONITEMMANAGEMENTSVC_QNAME);
    }

    public DocumentationItemManagementSvc(WebServiceFeature... features) {
        super(__getWsdlLocation(), DOCUMENTATIONITEMMANAGEMENTSVC_QNAME, features);
    }

    public DocumentationItemManagementSvc(URL wsdlLocation) {
        super(wsdlLocation, DOCUMENTATIONITEMMANAGEMENTSVC_QNAME);
    }

    public DocumentationItemManagementSvc(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DOCUMENTATIONITEMMANAGEMENTSVC_QNAME, features);
    }

    public DocumentationItemManagementSvc(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DocumentationItemManagementSvc(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DocumentationItemManagement
     */
    @WebEndpoint(name = "DocumentationItemManagementPort")
    public DocumentationItemManagement getDocumentationItemManagementPort() {
        return super.getPort(new QName("urn://bancodebogota.com/resources/classification/service/", "DocumentationItemManagementPort"), DocumentationItemManagement.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DocumentationItemManagement
     */
   @WebEndpoint(name = "DocumentationItemManagementPort") 
    public DocumentationItemManagement getDocumentationItemManagementPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn://bancodebogota.com/resources/classification/service/", "DocumentationItemManagementPort"), DocumentationItemManagement.class, features);
    }

    /**
     * 
     * @return
     *     returns DocumentationItemManagement
     */
    @WebEndpoint(name = "DocumentationItemManagementPort.0")
    public DocumentationItemManagement getDocumentationItemManagementPort0() {
        return super.getPort(new QName("urn://bancodebogota.com/resources/classification/service/", "DocumentationItemManagementPort.0"), DocumentationItemManagement.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DocumentationItemManagement
     */
    @WebEndpoint(name = "DocumentationItemManagementPort.0")
    public DocumentationItemManagement getDocumentationItemManagementPort0(WebServiceFeature... features) {
        return super.getPort(new QName("urn://bancodebogota.com/resources/classification/service/", "DocumentationItemManagementPort.0"), DocumentationItemManagement.class, features);
    }

    /**
     * 
     * @return
     *     returns DocumentationItemManagement
     */
    @WebEndpoint(name = "DocumentationItemManagementPort.1")
    public DocumentationItemManagement getDocumentationItemManagementPort1() {
        return super.getPort(new QName("urn://bancodebogota.com/resources/classification/service/", "DocumentationItemManagementPort.1"), DocumentationItemManagement.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DocumentationItemManagement
     */
    @WebEndpoint(name = "DocumentationItemManagementPort.1")
    public DocumentationItemManagement getDocumentationItemManagementPort1(WebServiceFeature... features) {
        return super.getPort(new QName("urn://bancodebogota.com/resources/classification/service/", "DocumentationItemManagementPort.1"), DocumentationItemManagement.class, features);
    }

    /**
     * 
     * @return
     *     returns DocumentationItemManagement
     */
    @WebEndpoint(name = "DocumentationItemManagementPort.2")
    public DocumentationItemManagement getDocumentationItemManagementPort2() {
        return super.getPort(new QName("urn://bancodebogota.com/resources/classification/service/", "DocumentationItemManagementPort.2"), DocumentationItemManagement.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DocumentationItemManagement
     */
    @WebEndpoint(name = "DocumentationItemManagementPort.2")
    public DocumentationItemManagement getDocumentationItemManagementPort2(WebServiceFeature... features) {
        return super.getPort(new QName("urn://bancodebogota.com/resources/classification/service/", "DocumentationItemManagementPort.2"), DocumentationItemManagement.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DOCUMENTATIONITEMMANAGEMENTSVC_EXCEPTION!= null) {
            throw DOCUMENTATIONITEMMANAGEMENTSVC_EXCEPTION;
        }
        return DOCUMENTATIONITEMMANAGEMENTSVC_WSDL_LOCATION;
    }

}
