
package wsproxy.proxy.onbase.com.bancodebogota.resources.classification.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DocumentationItemManagement", targetNamespace = "urn://bancodebogota.com/resources/classification/service/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    wsproxy.proxy.onbase.com.bancodebogota.ifx.base.v1.ObjectFactory.class,
    wsproxy.proxy.onbase.com.bancodebogota.ifx.base.v2.ObjectFactory.class,
    wsproxy.proxy.onbase.com.bancodebogota.resources.classification.event.ObjectFactory.class,
    wsproxy.proxy.onbase.com.bancodebogota.resources.classification.service.ObjectFactory.class,
    wsproxy.proxy.onbase.com.bancodebogota.resources.classification.v1.ObjectFactory.class,
    wsproxy.proxy.onbase.com.bancodebogota.resources.support.v1.ObjectFactory.class
})
public interface DocumentationItemManagement {


    /**
     * 
     * @param documentAddRq
     * @return
     *     returns com.bancodebogota.resources.classification.service.SetDocumentResponse
     * @throws SetDocumentFault_Exception
     */
    @WebMethod(action = "urn://bancodebogota.com/resources/classification/service/setDocument")
    @WebResult(name = "setDocumentResponse", targetNamespace = "urn://bancodebogota.com/resources/classification/service/", partName = "DocumentAddRs")
    public SetDocumentResponse setDocument(
        @WebParam(name = "setDocumentRequest", targetNamespace = "urn://bancodebogota.com/resources/classification/service/", partName = "DocumentAddRq")
        SetDocumentRequest documentAddRq)
        throws SetDocumentFault_Exception
    ;

    /**
     * 
     * @param indexedDocumentAddRq
     * @return
     *     returns com.bancodebogota.resources.classification.service.SetIndexedDocumentResponse
     * @throws SetIndexedDocumentFault_Exception
     */
    @WebMethod(action = "urn://bancodebogota.com/resources/classification/setIndexedDocument")
    @WebResult(name = "setIndexedDocumentResponse", targetNamespace = "urn://bancodebogota.com/resources/classification/service/", partName = "IndexedDocumentAddRs")
    public SetIndexedDocumentResponse setIndexedDocument(
        @WebParam(name = "setIndexedDocumentRequest", targetNamespace = "urn://bancodebogota.com/resources/classification/service/", partName = "IndexedDocumentAddRq")
        SetIndexedDocumentRequest indexedDocumentAddRq)
        throws SetIndexedDocumentFault_Exception
    ;

    /**
     * 
     * @param keywordsAddRq
     * @return
     *     returns com.bancodebogota.resources.classification.service.SetKeywordsResponse
     * @throws SetKeywordsFault_Exception
     */
    @WebMethod(action = "urn://bancodebogota.com/resources/classification/setKeywords")
    @WebResult(name = "setKeywordsResponse", targetNamespace = "urn://bancodebogota.com/resources/classification/service/", partName = "KeywordsAddRs")
    public SetKeywordsResponse setKeywords(
        @WebParam(name = "setKeywordsRequest", targetNamespace = "urn://bancodebogota.com/resources/classification/service/", partName = "KeywordsAddRq")
        SetKeywordsRequest keywordsAddRq)
        throws SetKeywordsFault_Exception
    ;

}
