
package wsproxy.proxy.onbase.com.bancodebogota.resources.classification.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "setIndexedDocumentFault", targetNamespace = "urn://bancodebogota.com/resources/classification/service/")
public class SetIndexedDocumentFault_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private SetIndexedDocumentFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public SetIndexedDocumentFault_Exception(String message, SetIndexedDocumentFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public SetIndexedDocumentFault_Exception(String message, SetIndexedDocumentFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.bancodebogota.resources.classification.service.SetIndexedDocumentFault
     */
    public SetIndexedDocumentFault getFaultInfo() {
        return faultInfo;
    }

}
