
package org.bancodebogota.gedebaso;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 *
 */
@WebService(name = "ServiceSoap", targetNamespace = "http://gedebaso.bancodebogota.org/")
@XmlSeeAlso({ ObjectFactory.class })
public interface ServiceSoap {


    /**
     *
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "TestServicio", action = "http://gedebaso.bancodebogota.org/TestServicio")
    @WebResult(name = "TestServicioResult", targetNamespace = "http://gedebaso.bancodebogota.org/")
    @RequestWrapper(localName = "TestServicio", targetNamespace = "http://gedebaso.bancodebogota.org/",
                    className = "org.bancodebogota.gedebaso.TestServicio")
    @ResponseWrapper(localName = "TestServicioResponse", targetNamespace = "http://gedebaso.bancodebogota.org/",
                     className = "org.bancodebogota.gedebaso.TestServicioResponse")
    public String testServicio();

    /**
     *
     * @param tipoDominio
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ListaDominios", action = "http://gedebaso.bancodebogota.org/ListaDominios")
    @WebResult(name = "ListaDominiosResult", targetNamespace = "http://gedebaso.bancodebogota.org/")
    @RequestWrapper(localName = "ListaDominios", targetNamespace = "http://gedebaso.bancodebogota.org/",
                    className = "org.bancodebogota.gedebaso.ListaDominios")
    @ResponseWrapper(localName = "ListaDominiosResponse", targetNamespace = "http://gedebaso.bancodebogota.org/",
                     className = "org.bancodebogota.gedebaso.ListaDominiosResponse")
    public String listaDominios(@WebParam(name = "tipo_dominio", targetNamespace = "http://gedebaso.bancodebogota.org/")
                                String tipoDominio);

    /**
     *
     * @param extension
     * @param domain
     * @param user
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "VerificaExistenciaUsuarioxNombreDominio",
               action = "http://gedebaso.bancodebogota.org/VerificaExistenciaUsuarioxNombreDominio")
    @WebResult(name = "VerificaExistenciaUsuarioxNombreDominioResult",
               targetNamespace = "http://gedebaso.bancodebogota.org/")
    @RequestWrapper(localName = "VerificaExistenciaUsuarioxNombreDominio",
                    targetNamespace = "http://gedebaso.bancodebogota.org/",
                    className = "org.bancodebogota.gedebaso.VerificaExistenciaUsuarioxNombreDominio")
    @ResponseWrapper(localName = "VerificaExistenciaUsuarioxNombreDominioResponse",
                     targetNamespace = "http://gedebaso.bancodebogota.org/",
                     className = "org.bancodebogota.gedebaso.VerificaExistenciaUsuarioxNombreDominioResponse")
    public String verificaExistenciaUsuarioxNombreDominio(@WebParam(name = "domain",
                                                                    targetNamespace =
                                                                    "http://gedebaso.bancodebogota.org/") String domain,
                                                          @WebParam(name = "extension",
                                                                    targetNamespace =
                                                                    "http://gedebaso.bancodebogota.org/")
                                                          String extension,
                                                          @WebParam(name = "user",
                                                                    targetNamespace =
                                                                    "http://gedebaso.bancodebogota.org/") String user);

    /**
     *
     * @param extension
     * @param domain
     * @param password
     * @param user
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "verifica_usuario_clave",
               action = "http://gedebaso.bancodebogota.org/verifica_usuario_clave")
    @WebResult(name = "verifica_usuario_claveResult", targetNamespace = "http://gedebaso.bancodebogota.org/")
    @RequestWrapper(localName = "verifica_usuario_clave", targetNamespace = "http://gedebaso.bancodebogota.org/",
                    className = "org.bancodebogota.gedebaso.VerificaUsuarioClave")
    @ResponseWrapper(localName = "verifica_usuario_claveResponse",
                     targetNamespace = "http://gedebaso.bancodebogota.org/",
                     className = "org.bancodebogota.gedebaso.VerificaUsuarioClaveResponse")
    public String verificaUsuarioClave(@WebParam(name = "domain",
                                                 targetNamespace = "http://gedebaso.bancodebogota.org/") String domain,
                                       @WebParam(name = "extension",
                                                 targetNamespace = "http://gedebaso.bancodebogota.org/")
                                       String extension,
                                       @WebParam(name = "user", targetNamespace = "http://gedebaso.bancodebogota.org/")
                                       String user,
                                       @WebParam(name = "password",
                                                 targetNamespace = "http://gedebaso.bancodebogota.org/")
                                       String password);

}
