
package org.bancodebogota.gedebaso;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 *
 */
@WebServiceClient(name = "Service", targetNamespace = "http://gedebaso.bancodebogota.org/",
                  wsdlLocation = "http://10.85.150.238/wsautenticacion/service.asmx?WSDL")
public class Service extends javax.xml.ws.Service {

    private final static URL SERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.bancodebogota.gedebaso.Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.bancodebogota.gedebaso.Service.class.getResource(".");
            url = new URL(baseUrl, "http://10.85.150.238/wsautenticacion/service.asmx?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://10.85.150.238/wsautenticacion/service.asmx?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SERVICE_WSDL_LOCATION = url;
    }

    public Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Service() {
        super(SERVICE_WSDL_LOCATION, new QName("http://gedebaso.bancodebogota.org/", "Service"));
    }

    /**
     *
     * @return
     *     returns ServiceSoap
     */
    @WebEndpoint(name = "ServiceSoap")
    public ServiceSoap getServiceSoap() {
        return super.getPort(new QName("http://gedebaso.bancodebogota.org/", "ServiceSoap"), ServiceSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceSoap
     */
    @WebEndpoint(name = "ServiceSoap")
    public ServiceSoap getServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://gedebaso.bancodebogota.org/", "ServiceSoap"), ServiceSoap.class,
                             features);
    }

}
